Added tryhackme
themorpheustutorials/resources pull request #8
Opened 2021-07-07 16:47 UTC by Ari24-cb24

**Beschreibung**
Tryhackme zu it-sec hinzugefügt

2021-07-08 20:49 UTC, felbinger approved these changes

2021-07-08 20:49 UTC, felbinger commented on docs/mathematik.md
> +- Mathematische Beweise: How to think mathematically von Kevin Houston
Wenn möglich noch Links zu den Büchern hinzufügen :wink:

2021-07-11 08:04 UTC, MarcelCoding requested changes
Bitte Konflikte beheben.

2021-07-12 18:47 UTC, Ari24-cb24 commented
Kannst du mir grad mal ein wenig auf die Sprünge helfen?

2021-07-12 19:20 UTC, MarcelCoding commented
![image](https://user-images.githubusercontent.com/34819524/125343942-f7432f00-e356-11eb-9d5a-04c94f9ce883.png)
@Ari24-cb24

2021-07-13 11:40 UTC, Ari24-cb24 commented
Ich werde daraus leider nicht schlau, was genau conflicted. Sehe nur, dass all meine Änderungen mit einem Roten Rand versehen sind.

2021-07-13 13:06 UTC, MarcelCoding commented
@Ari24-cb24 ich kann es dir demnächst mal auf Discord erklären.

2021-07-14 13:47 UTC, merged